id: I19183F4B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T08:02:42+00:00'
last_modified: '2022-06-08T08:18:28.278137+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1EE28
  title: ལེགས་བཤད་རིན་པོ་ཆེའི་གཏེར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    D1EE:
      image_group_id: I1KG16848
      title: ''
      total_pages: 118
      order: 1
      base_file: D1EE.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
