id: P008260
initial_creation_type: ocr
source_metadata:
  id: bdr:W1EE28
  title: ལེགས་བཤད་རིན་པོ་ཆེའི་གཏེར།
  author: ''
  volumes:
    97fbb3d33f57481aa9053cec082871cf:
      image_group_id: I1KG16848
      title: ''
      volume_number: 1
      total_pages: 118
